In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 28.8 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.3

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pyreadstat

/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2017/pod_17_renda-per-capita_tab06.xlsx
/kaggle/input/datasets/lefcollado/pod-2017/OD_2017_v1.sav

## Loading data

In [3]:
pod_17, meta = pyreadstat.read_sav("/kaggle/input/datasets/lefcollado/pod-2017/OD_2017_v1.sav")
pod_17.shape

(183092, 128)

In [4]:
pod_17.head()

,zona,muni_dom,co_dom_x,co_dom_y,id_dom,f_dom,fe_dom,dom,cd_entre,data,...,modoprin,tipvg,pag_viag,tp_esauto,vl_est,pe_bici,via_bici,tp_esbici,distancia,id_ordem
0,1.0,36.0,333743.0,7394463.0,00010001,1.0,15.416667,1.0,1.0,06092017,...,16.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,639.132224,1.0
1,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,16.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,639.132224,2.0
2,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,6651.767885,3.0
3,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,4243.298717,4.0
4,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4557.622187,5.0

In [5]:
type(pod_17)

pandas.core.frame.DataFrame

## Creating dictionary
Creating a list of variables to match the dictionary providaded by Metro

In [6]:
col17 = list(pod_17.columns)
col17_df = pd.DataFrame(col17, columns=["column_name"])
col17_df.to_excel("pod_17_columns.xlsx", index=False)

## First assessment of dataframe

In [7]:
na_df = pod_17.isna().sum().sort_values(ascending=False).to_frame(name="missing_count")

na_df.to_excel("pod_17_tot_NAs.xlsx")

### Creating new dataframe with variables of interest

In [8]:
pod_17_2 = pod_17[
    [
        "id_ordem",
        "zona",
        "modoprin",
        "distancia",
        "dia_sem",
        "motivo_o",
        "motivo_d",
        "h_saida",
        "duracao",
        "idade",
        "sexo",
        "grau_ins",
        "qt_auto",
        "cd_ativi",
        "co_ren_i",
        "vl_ren_i",
        "renda_fa",
        "trab1_re",
        "ocup1",
        "setor1",
        "vinc1",
    ]
].copy()

In [9]:
pod_17_2.shape

(183092, 21)

In [10]:
pod_17_2.head()

,id_ordem,zona,modoprin,distancia,dia_sem,motivo_o,motivo_d,h_saida,duracao,idade,...,grau_ins,qt_auto,cd_ativi,co_ren_i,vl_ren_i,renda_fa,trab1_re,ocup1,setor1,vinc1
0,1.0,1.0,16.0,639.132224,3.0,8.0,3.0,5.0,10.0,59.0,...,3.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,13.0,1.0
1,2.0,1.0,16.0,639.132224,3.0,3.0,8.0,15.0,10.0,59.0,...,3.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,13.0,1.0
2,3.0,1.0,1.0,6651.767885,3.0,8.0,3.0,9.0,50.0,21.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0
3,4.0,1.0,1.0,4243.298717,3.0,3.0,4.0,17.0,60.0,21.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0
4,5.0,1.0,12.0,4557.622187,3.0,4.0,8.0,22.0,40.0,21.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0

#### NA count in each column

In [11]:
pod_17_2.isna().sum()

id_ordem         0
zona             0
modoprin     25100
distancia    25100
dia_sem      25100
motivo_o     25100
motivo_d     25100
h_saida      25100
duracao      25100
idade            0
sexo             0
grau_ins         0
qt_auto       4162
cd_ativi         0
co_ren_i         0
vl_ren_i     68231
renda_fa         0
trab1_re     80374
ocup1        80374
setor1       80374
vinc1        80374
dtype: int64

### New dataframe without NAs in the column 'Main mode of transport'"

In [12]:
pod_17_2 = pod_17_2[pod_17_2["modoprin"].notna()].copy()

In [13]:
pod_17_2.isna().sum()

id_ordem         0
zona             0
modoprin         0
distancia        0
dia_sem          0
motivo_o         0
motivo_d         0
h_saida          0
duracao          0
idade            0
sexo             0
grau_ins         0
qt_auto       3567
cd_ativi         0
co_ren_i         0
vl_ren_i     60291
renda_fa         0
trab1_re     60784
ocup1        60784
setor1       60784
vinc1        60784
dtype: int64

In [14]:
pod_17_2.shape

(157992, 21)

## Cleaning and formatting specific columns

### Quantity of cars per household

!!! o que fazer com os NAs??

In [15]:
pod_17_2["qt_auto"].value_counts(dropna=False)

qt_auto
1.0    74051
0.0    52206
2.0    23191
3.0     4025
NaN     3567
4.0      804
5.0      122
8.0       24
6.0        2
Name: count, dtype: int64

### Individual income

In [16]:
pod_17_2["vl_ren_i"].describe()

count    97701.000000
mean      1768.548428
std       3227.951877
min          0.000000
25%          0.000000
50%        954.000000
75%       2000.000000
max      55000.000000
Name: vl_ren_i, dtype: float64

### Creating target variable

In [17]:
pod_17_2["modoprin"].value_counts(dropna=False)

modoprin
16.0    48285
9.0     37005
4.0     18612
1.0     14077
10.0    13308
8.0      6463
5.0      5565
13.0     3045
2.0      2926
6.0      2795
12.0     2333
15.0     1294
11.0      916
7.0       698
17.0      395
14.0      274
3.0         1
Name: count, dtype: int64

In [18]:
pod_17_2["modoprin_y"] = pod_17_2["modoprin"].isin([15, 16]).astype(int)

In [19]:
pod_17_2["modoprin_y"].value_counts(dropna=False)

modoprin_y
0    108413
1     49579
Name: count, dtype: int64

### Reason for the trip

In [20]:
pod_17_2["motivo_o"].value_counts(dropna=False)

motivo_o
8.0     71395
3.0     27371
4.0     25480
2.0      6900
10.0     5511
1.0      5289
5.0      4491
7.0      4074
6.0      3887
11.0     3293
9.0       301
Name: count, dtype: int64

#### Transform motivo_o and motivo_d into categorical variable with labels

In [21]:
motivo_labels = {
    1: "Trabalho Indústria",
    2: "Trabalho Comércio",
    3: "Trabalho Serviços",
    4: "Escola/Educação",
    5: "Compras",
    6: "Médico/Dentista/Saúde",
    7: "Recreação/Visitas/Lazer",
    8: "Residência",
    9: "Procurar Emprego",
    10: "Assuntos Pessoais",
    11: "Refeição"
}

pod_17_2["motivo_o_cat"] = pd.Categorical(
    pod_17_2["motivo_o"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

In [22]:
pod_17_2["motivo_o_cat"].value_counts(dropna=False)

motivo_o_cat
Residência                 71395
Trabalho Serviços          27371
Escola/Educação            25480
Trabalho Comércio           6900
Assuntos Pessoais           5511
Trabalho Indústria          5289
Compras                     4491
Recreação/Visitas/Lazer     4074
Médico/Dentista/Saúde       3887
Refeição                    3293
Procurar Emprego             301
Name: count, dtype: int64

In [23]:
pod_17_2["motivo_d_cat"] = pd.Categorical(
    pod_17_2["motivo_d"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

In [24]:
pod_17_2["motivo_d_cat"].value_counts(dropna=False)

motivo_d_cat
Residência                 71188
Trabalho Serviços          27425
Escola/Educação            25496
Trabalho Comércio           6904
Assuntos Pessoais           5527
Trabalho Indústria          5302
Compras                     4468
Recreação/Visitas/Lazer     4193
Médico/Dentista/Saúde       3903
Refeição                    3285
Procurar Emprego             301
Name: count, dtype: int64

#### Grouping categories

In [25]:
pod_17_2["motivo_o_group"] = pod_17_2["motivo_o_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [26]:
pod_17_2["motivo_o_group"] = pd.Categorical(
    pod_17_2["motivo_o_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [27]:
pod_17_2["motivo_o_group"].value_counts(dropna=False)

motivo_o_group
Home                71395
Work                39560
Education           25480
Personal Matters    21557
Name: count, dtype: int64

In [28]:
pod_17_2["motivo_d_group"] = pod_17_2["motivo_d_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [29]:
pod_17_2["motivo_d_group"] = pd.Categorical(
    pod_17_2["motivo_d_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [30]:
pod_17_2["motivo_d_group"].value_counts(dropna=False)

motivo_d_group
Home                71188
Work                39631
Education           25496
Personal Matters    21677
Name: count, dtype: int64

In [31]:
pod_17_2["motivo_d_group"].dtype

CategoricalDtype(categories=['Home', 'Work', 'Education', 'Personal Matters'], ordered=False, categories_dtype=object)

#### Join the two columns

In [32]:
pod_17_2["motivo"] = pod_17_2.apply(
    lambda row:
        "Home - Work"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Work"}
        else "Home - Personal Matters"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Personal Matters"}
        else "Home - Education"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Education"}
        else "Others",
    axis=1
)

pod_17_2["motivo"].value_counts(dropna=False)

motivo
Home - Work                66046
Home - Education           46110
Home - Personal Matters    30427
Others                     15409
Name: count, dtype: int64

### Level of education

In [33]:
grau_labels = {
    1: "No Formal Education/Incomplete Primary Education",
    2: "Primary Education Completed / Lower Secondary Incomplete",
    3: "Lower Secondary Completed / Upper Secondary Incomplete",
    4: "Upper Secondary Completed / Higher Education Incomplete",
    5: "Higher Education Completed"
}

pod_17_2["grau_ins"] = pd.Categorical(
    pod_17_2["grau_ins"].map(grau_labels),
    categories=list(grau_labels.values()),
    ordered=True
)

In [34]:
pod_17_2["grau_ins"].value_counts(dropna=False)

grau_ins
Upper Secondary Completed / Higher Education Incomplete     51895
Higher Education Completed                                  47591
No Formal Education/Incomplete Primary Education            21621
Lower Secondary Completed / Upper Secondary Incomplete      19172
Primary Education Completed / Lower Secondary Incomplete    17713
Name: count, dtype: int64

### Currently working?

In [35]:
pod_17_2["cd_ativi"].value_counts(dropna=False)

cd_ativi
1.0    89628
8.0    28199
4.0    12444
5.0     8397
2.0     7203
7.0     6572
6.0     5156
3.0      393
Name: count, dtype: int64

In [36]:
pod_17_2["curr_work"] = (pod_17_2["cd_ativi"] == 1).astype(int)
pod_17_2["curr_work"].value_counts(dropna=False)

curr_work
1    89628
0    68364
Name: count, dtype: int64

### Days of the week

In [37]:
pod_17_2["dia_sem"].value_counts(dropna=False)

dia_sem
6.0    57818
5.0    29191
3.0    28290
4.0    24896
2.0    17797
Name: count, dtype: int64

In [38]:
day_labels = {
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}

pod_17_2["dia_sem"] = pd.Categorical(
    pod_17_2["dia_sem"].map(day_labels),
    categories=list(day_labels.values()),
    ordered=True
)

pod_17_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       57818
Thursday     29191
Tuesday      28290
Wednesday    24896
Monday       17797
Name: count, dtype: int64

### Time of day of trip start

In [39]:
pod_17_2["h_saida"].dtype

dtype('float64')

In [40]:
pod_17_2["h_saida"].head()

0     5.0
1    15.0
2     9.0
3    17.0
4    22.0
Name: h_saida, dtype: float64

In [41]:
pod_17_2["h_saida"].describe()

count    157992.000000
mean         12.735487
std           4.863167
min           0.000000
25%           8.000000
50%          12.000000
75%          17.000000
max          23.000000
Name: h_saida, dtype: float64

In [42]:
pod_17_2["h_saida_period"] = pd.cut(
    pod_17_2["h_saida"],
    bins=[0, 5, 10, 13, 18, 24],
    labels=["Dawn", "Morning", "Lunch", "Afternoon", "Night"],
    include_lowest=True,
    right=True
)

pod_17_2["h_saida_period"].value_counts(dropna=False)

h_saida_period
Afternoon    50367
Morning      47419
Lunch        38159
Night        16830
Dawn          5217
Name: count, dtype: int64

### In which sector is your main occupation?

In [43]:
pod_17_2["setor1"].value_counts(dropna=False)

setor1
NaN     60784
14.0    20255
4.0     17250
12.0    11923
3.0      9494
11.0     7106
10.0     6967
9.0      4811
2.0      4244
7.0      3625
13.0     3616
8.0      3038
6.0      2864
5.0      1816
1.0       199
Name: count, dtype: int64

In [44]:
sector_map = {
    1: "Agriculture",
    2: "Construction",
    3: "Industry",
    4: "Commerce",
    13: "Public Administration"
}

pod_17_2["sector_comb"] = pod_17_2["setor1"].map(sector_map)

pod_17_2["sector_comb"] = pod_17_2["sector_comb"].mask(
    pod_17_2["sector_comb"].isna() & pod_17_2["setor1"].notna(),
    "Services"
)

pod_17_2["sector_comb"].value_counts(dropna=False)

sector_comb
Services                 62405
NaN                      60784
Commerce                 17250
Industry                  9494
Construction              4244
Public Administration     3616
Agriculture                199
Name: count, dtype: int64

### Emplyment relationship

In [45]:
pod_17_2["vinc1"].value_counts(dropna=False)

vinc1
NaN    60784
1.0    49039
4.0    20438
2.0     6271
6.0     6228
3.0     5451
7.0     5345
5.0     4019
8.0      417
Name: count, dtype: int64

In [46]:
empl_map = {
    1: "Wage and salaried employees",
    2: "Wage and salaried employees",
    3: "Public sector",
    4: "Self-employed"
}

pod_17_2["empl_relat"] = pod_17_2["vinc1"].map(empl_map)

pod_17_2["empl_relat"] = pod_17_2["empl_relat"].mask(
    pod_17_2["empl_relat"].isna() & pod_17_2["vinc1"].notna(),
    "Other"
)

pod_17_2["empl_relat"].value_counts(dropna=False)

empl_relat
NaN                            60784
Wage and salaried employees    55310
Self-employed                  20438
Other                          16009
Public sector                   5451
Name: count, dtype: int64

### Gender

In [47]:
pod_17_2["gender"] = pod_17_2["sexo"].map({
    1: "Male",
    2: "Female"
})

pod_17_2["gender"].value_counts(dropna=False)

gender
Male      79122
Female    78870
Name: count, dtype: int64

## Adding external data for income per capita in the zone of home address

In [48]:
renda_zona = pd.read_excel(
    "/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2017/pod_17_renda-per-capita_tab06.xlsx"
)

pod_17_2 = pod_17_2.merge(
    renda_zona[["zona", "renda_pc"]],
    on="zona",
    how="left"
).rename(columns={"renda_pc": "pc_income"})

pod_17_2[["zona", "pc_income"]].head()

   zona    pc_income
0   1.0  1151.811909
1   1.0  1151.811909
2   1.0  1151.811909
3   1.0  1151.811909
4   1.0  1151.811909

In [49]:
pod_17_2["pc_income"].isna().sum()

np.int64(0)

### Age intervals

In [50]:
pod_17_2["age"] = pd.cut(
    pod_17_2["idade"],
    bins=[-float("inf"), 15, 29, 59, float("inf")],
    labels=[
        "15 years old or less",
        "16 to 29 years old",
        "30 to 59 years old",
        "60 years old or older"
    ]
)

pod_17_2["age"].value_counts(dropna=False)

age
30 to 59 years old       76538
16 to 29 years old       33485
15 years old or less     25720
60 years old or older    22249
Name: count, dtype: int64

In [51]:
pod_17_2.loc[pod_17_2["idade"] <= 15, "idade"].value_counts(dropna=False).sort_index()

idade
1.0     1148
2.0     1125
3.0     1263
4.0     1483
5.0     1633
6.0     1634
7.0     1836
8.0     1834
9.0     1823
10.0    1797
11.0    1846
12.0    2130
13.0    1961
14.0    2192
15.0    2015
Name: count, dtype: int64

## Creating new dataframe with constructed variables

In [52]:
summary = pd.DataFrame({
    "column": pod_17_2.columns,
    "dtype": pod_17_2.dtypes.values,
    "na_count": pod_17_2.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_17_2[col]) for col in pod_17_2.columns
]

summary.style.set_properties(**{"text-align": "left"})

In [53]:
pod_17_3 = pod_17_2[
    [
        "id_ordem",
        "zona",
        "modoprin_y",
        "distancia",
        "age",
        "gender",
        "grau_ins",
        "renda_fa",
        "pc_income",
        "qt_auto",
        "motivo",
        "h_saida_period",
        "dia_sem",
        "curr_work",
        "sector_comb",
        "empl_relat"
    ]
].copy()

In [54]:
pod_17_3.shape

(157992, 16)

In [55]:
pod_17_3.head()

,id_ordem,zona,modoprin_y,distancia,age,gender,grau_ins,renda_fa,pc_income,qt_auto,motivo,h_saida_period,dia_sem,curr_work,sector_comb,empl_relat
0,1.0,1.0,1,639.132224,30 to 59 years old,Female,Lower Secondary Completed / Upper Secondary In...,2732.57591,1151.811909,0.0,Home - Work,Dawn,Tuesday,1,Public Administration,Wage and salaried employees
1,2.0,1.0,1,639.132224,30 to 59 years old,Female,Lower Secondary Completed / Upper Secondary In...,2732.57591,1151.811909,0.0,Home - Work,Afternoon,Tuesday,1,Public Administration,Wage and salaried employees
2,3.0,1.0,0,6651.767885,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,2732.57591,1151.811909,0.0,Home - Work,Morning,Tuesday,1,Services,Wage and salaried employees
3,4.0,1.0,0,4243.298717,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,2732.57591,1151.811909,0.0,Others,Afternoon,Tuesday,1,Services,Wage and salaried employees
4,5.0,1.0,0,4557.622187,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,2732.57591,1151.811909,0.0,Home - Education,Night,Tuesday,1,Services,Wage and salaried employees

In [56]:
summary = pd.DataFrame({
    "column": pod_17_3.columns,
    "dtype": pod_17_3.dtypes.values,
    "na_count": pod_17_3.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_17_3[col]) for col in pod_17_3.columns
]

summary.style.set_properties(**{"text-align": "left"})

### Checking age intervals

In [57]:
pod_17_2["age"].value_counts(dropna=False)

age
30 to 59 years old       76538
16 to 29 years old       33485
15 years old or less     25720
60 years old or older    22249
Name: count, dtype: int64

In [58]:
pod_17_3[pod_17_3["age"] == "15 years old or less"]["curr_work"].value_counts(dropna=False)

curr_work
0    25636
1       84
Name: count, dtype: int64

### Saving new dataset

In [59]:
pod_17_3.to_parquet("pod_17_3.parquet")