In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.3-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 68.0 MB/s eta 0:00:00
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.3

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pyreadstat

/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2023/pod_23_renda-per-capita_tab06.xlsx
/kaggle/input/datasets/lefcollado/pod-2023/Banco2023_divulgacao_190225.sav

## Loading data

In [3]:
pod_23, meta = pyreadstat.read_sav("/kaggle/input/datasets/lefcollado/pod-2023/Banco2023_divulgacao_190225.sav")
pod_23.shape

(143038, 147)

In [4]:
pod_23.head()

,zona,muni_dom,co_dom_x,co_dom_y,id_dom,f_dom,Fe_dom,dom,cd_entre,DATA,...,duracao,modoprin,tipvg,tp_esauto,vl_est,pe_bici,tp_estbici,prop_bici,distancia,id_ordem
0,1.0,36.0,333725.0,7394554.0,,1.0,32.34,1.0,1.0,2024-04-17,...,30.0,16.0,4.0,NaN,NaN,7.0,2.0,1.0,1518.600013,1.0
1,1.0,36.0,333725.0,7394554.0,00100001,0.0,32.34,1.0,1.0,2024-04-17,...,30.0,16.0,4.0,NaN,NaN,9.0,2.0,1.0,1518.600013,2.0
2,1.0,36.0,333725.0,7394554.0,00100002,1.0,32.34,2.0,1.0,2024-04-17,...,30.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,8350.069281,3.0
3,1.0,36.0,333725.0,7394554.0,00100002,0.0,32.34,2.0,1.0,2024-04-17,...,25.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,8350.069281,4.0
4,1.0,36.0,333725.0,7394554.0,00100002,0.0,32.34,2.0,1.0,2024-04-17,...,30.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,10346.375791,5.0

In [5]:
type(pod_23)

pandas.core.frame.DataFrame

## Creating dictionary
Creating a list of variables to match the dictionary providaded by Metro

In [6]:
col23 = list(pod_23.columns)
col23_df = pd.DataFrame(col23, columns=["column_name"])
col23_df.to_excel("pod_23_columns.xlsx", index=False)

## First assessment of dataframe

In [7]:
na_df = pod_23.isna().sum().sort_values(ascending=False).to_frame(name="missing_count")

na_df.to_excel("pod_23_tot_NAs.xlsx")

### Creating new dataframe with variables of interest

In [8]:
pod_23_2 = pod_23[
    [
        "id_ordem",
        "zona",
        "modoprin",
        "distancia",
        "dia_sem",
        "motivo_o",
        "motivo_d",
        "h_saida",
        "idade",
        "sexo",
        "grau_ins",
        "qt_auto",
        "cd_ativi",
        "renda_fa",
        "setor1",
        "vinc1",
    ]
].copy()

In [9]:
pod_23_2.shape

(143038, 16)

In [10]:
pod_23_2.head()

,id_ordem,zona,modoprin,distancia,dia_sem,motivo_o,motivo_d,h_saida,idade,sexo,grau_ins,qt_auto,cd_ativi,renda_fa,setor1,vinc1
0,1.0,1.0,16.0,1518.600013,3.0,8.0,2.0,11.0,67.0,1.0,4.0,1.0,4.0,7000.0,9.0,6.0
1,2.0,1.0,16.0,1518.600013,3.0,2.0,8.0,15.0,67.0,1.0,4.0,1.0,4.0,7000.0,9.0,6.0
2,3.0,1.0,12.0,8350.069281,3.0,8.0,7.0,18.0,22.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0
3,4.0,1.0,12.0,8350.069281,3.0,7.0,8.0,23.0,22.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0
4,5.0,1.0,12.0,10346.375791,3.0,8.0,7.0,13.0,21.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0

NA count in each column

In [11]:
pod_23_2.isna().sum()

id_ordem         0
zona             0
modoprin     30125
distancia    30125
dia_sem      30125
motivo_o     30125
motivo_d     30125
h_saida      30125
idade            0
sexo             0
grau_ins         0
qt_auto        179
cd_ativi         0
renda_fa         0
setor1       63696
vinc1        63696
dtype: int64

### New dataframe without NAs in the column 'Main mode of transport'"

In [12]:
pod_23_2 = pod_23_2[pod_23_2["modoprin"].notna()].copy()

In [13]:
pod_23_2.isna().sum()

id_ordem         0
zona             0
modoprin         0
distancia        0
dia_sem          0
motivo_o         0
motivo_d         0
h_saida          0
idade            0
sexo             0
grau_ins         0
qt_auto        110
cd_ativi         0
renda_fa         0
setor1       43538
vinc1        43538
dtype: int64

In [14]:
pod_23_2.shape

(112913, 16)

## Cleaning and formatting specific columns

### Quantity of cars per household

!!! o que fazer com os NAs??

In [15]:
pod_23_2["qt_auto"].value_counts(dropna=False)

qt_auto
1.0    55889
0.0    39476
2.0    14721
3.0     2229
4.0      415
NaN      110
5.0       37
9.0       22
6.0       14
Name: count, dtype: int64

### Creating independent variable

In [16]:
pod_23_2["modoprin"].value_counts(dropna=False)

modoprin
17.0    29962
9.0     27771
4.0     12466
1.0      9367
10.0     8567
8.0      5930
12.0     4229
6.0      3848
13.0     3015
5.0      2494
2.0      2479
16.0      970
7.0       741
11.0      485
14.0      276
18.0      208
3.0        81
15.0       24
Name: count, dtype: int64

In [17]:
pod_23_2["modoprin_y"] = pod_23_2["modoprin"].isin([16, 17]).astype(int)

In [18]:
pod_23_2["modoprin_y"].value_counts(dropna=False)

modoprin_y
0    81981
1    30932
Name: count, dtype: int64

### Reason for the trip

In [19]:
pod_23_2["motivo_o"].value_counts(dropna=False)

motivo_o
8.0     54086
3.0     18747
4.0     18082
2.0      5266
1.0      3417
5.0      3206
6.0      3171
10.0     3124
7.0      2762
11.0      955
9.0        97
Name: count, dtype: int64

Transform motivo_o and motivo_d into categorical variable with labels

In [20]:
motivo_labels = {
    1: "Trabalho Indústria",
    2: "Trabalho Comércio",
    3: "Trabalho Serviços",
    4: "Escola/Educação",
    5: "Compras",
    6: "Médico/Dentista/Saúde",
    7: "Recreação/Visitas/Lazer",
    8: "Residência",
    9: "Procurar Emprego",
    10: "Assuntos Pessoais",
    11: "Refeição"
}

pod_23_2["motivo_o_cat"] = pd.Categorical(
    pod_23_2["motivo_o"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

pod_23_2["motivo_o_cat"].value_counts(dropna=False)

motivo_o_cat
Residência                 54086
Trabalho Serviços          18747
Escola/Educação            18082
Trabalho Comércio           5266
Trabalho Indústria          3417
Compras                     3206
Médico/Dentista/Saúde       3171
Assuntos Pessoais           3124
Recreação/Visitas/Lazer     2762
Refeição                     955
Procurar Emprego              97
Name: count, dtype: int64

In [21]:
pod_23_2["motivo_d_cat"] = pd.Categorical(
    pod_23_2["motivo_d"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

pod_23_2["motivo_d_cat"].value_counts()

motivo_d_cat
Residência                 53837
Trabalho Serviços          18834
Escola/Educação            18116
Trabalho Comércio           5286
Trabalho Indústria          3511
Compras                     3210
Médico/Dentista/Saúde       3170
Assuntos Pessoais           3050
Recreação/Visitas/Lazer     2857
Refeição                     944
Procurar Emprego              98
Name: count, dtype: int64

#### Grouping categories

In [22]:
pod_23_2["motivo_o_group"] = pod_23_2["motivo_o_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [23]:
pod_23_2["motivo_o_group"] = pd.Categorical(
    pod_23_2["motivo_o_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [24]:
pod_23_2["motivo_o_group"].value_counts(dropna=False)

motivo_o_group
Home                54086
Work                27430
Education           18082
Personal Matters    13315
Name: count, dtype: int64

In [25]:
pod_23_2["motivo_d_group"] = pod_23_2["motivo_d_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [26]:
pod_23_2["motivo_d_group"] = pd.Categorical(
    pod_23_2["motivo_d_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [27]:
pod_23_2["motivo_d_group"].value_counts()

motivo_d_group
Home                53837
Work                27631
Education           18116
Personal Matters    13329
Name: count, dtype: int64

In [28]:
pod_23_2["motivo_d_group"].dtype

CategoricalDtype(categories=['Home', 'Work', 'Education', 'Personal Matters'], ordered=False, categories_dtype=object)

#### Join the two columns

In [29]:
pod_23_2["motivo"] = pod_23_2.apply(
    lambda row:
        "Home - Work"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Work"}
        else "Home - Personal Matters"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Personal Matters"}
        else "Home - Education"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Education"}
        else "Others",
    axis=1
)

pod_23_2["motivo"].value_counts(dropna=False)

motivo
Home - Work                50955
Home - Education           34059
Home - Personal Matters    22909
Others                      4990
Name: count, dtype: int64

### Level of education

In [30]:
grau_labels = {
    1: "No Formal Education/Incomplete Primary Education",
    2: "Primary Education Completed / Lower Secondary Incomplete",
    3: "Lower Secondary Completed / Upper Secondary Incomplete",
    4: "Upper Secondary Completed / Higher Education Incomplete",
    5: "Higher Education Completed"
}

pod_23_2["grau_ins"] = pd.Categorical(
    pod_23_2["grau_ins"].map(grau_labels),
    categories=list(grau_labels.values()),
    ordered=True
)

pod_23_2["grau_ins"].value_counts()

grau_ins
Upper Secondary Completed / Higher Education Incomplete     38060
Higher Education Completed                                  34967
No Formal Education/Incomplete Primary Education            14209
Lower Secondary Completed / Upper Secondary Incomplete      13443
Primary Education Completed / Lower Secondary Incomplete    12234
Name: count, dtype: int64

### Currently working?

In [31]:
pod_23_2["cd_ativi"].value_counts(dropna=False)

cd_ativi
1.0    66240
8.0    20018
4.0    11014
5.0     4942
7.0     4041
6.0     3816
2.0     2654
3.0      188
Name: count, dtype: int64

In [32]:
pod_23_2["curr_work"] = (pod_23_2["cd_ativi"] == 1).astype(int)
pod_23_2["curr_work"].value_counts()

curr_work
1    66240
0    46673
Name: count, dtype: int64

### Days of the week

In [33]:
pod_23_2["dia_sem"].value_counts()

dia_sem
6.0    34125
3.0    26811
2.0    20814
4.0    16348
5.0    14814
0.0        1
Name: count, dtype: int64

In [34]:
day_labels = {
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}

pod_23_2["dia_sem"] = pd.Categorical(
    pod_23_2["dia_sem"].map(day_labels),
    categories=list(day_labels.values()),
    ordered=True
)

pod_23_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       34125
Tuesday      26811
Monday       20814
Wednesday    16348
Thursday     14814
NaN              1
Name: count, dtype: int64

In [35]:
pod_23_2 = pod_23_2[pod_23_2["dia_sem"].notna()].copy()

In [36]:
pod_23_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       34125
Tuesday      26811
Monday       20814
Wednesday    16348
Thursday     14814
Name: count, dtype: int64

### Time of day of trip start

In [37]:
pod_23_2["h_saida"].dtype

dtype('float64')

In [38]:
pod_23_2["h_saida"].head()

0    11.0
1    15.0
2    18.0
3    23.0
4    13.0
Name: h_saida, dtype: float64

In [39]:
pod_23_2["h_saida"].describe()

count    112912.000000
mean         12.444443
std           4.927284
min           0.000000
25%           8.000000
50%          12.000000
75%          17.000000
max          23.000000
Name: h_saida, dtype: float64

In [40]:
pod_23_2["h_saida_period"] = pd.cut(
    pod_23_2["h_saida"],
    bins=[0, 5, 10, 13, 18, 24],
    labels=["Dawn", "Morning", "Lunch", "Afternoon", "Night"],
    include_lowest=True,
    right=True
)

pod_23_2["h_saida_period"].value_counts()

h_saida_period
Morning      37698
Afternoon    36393
Lunch        23779
Night        10811
Dawn          4231
Name: count, dtype: int64

### In which sector is your main occupation?

In [41]:
pod_23_2["setor1"].value_counts(dropna=False)

setor1
NaN     43538
4.0     13649
14.0    10921
12.0    10150
3.0      6690
10.0     6492
11.0     4874
2.0      3435
9.0      2902
8.0      2318
7.0      2201
13.0     2151
6.0      1845
5.0      1629
1.0       117
Name: count, dtype: int64

In [42]:
sector_map = {
    1: "Agriculture",
    2: "Construction",
    3: "Industry",
    4: "Commerce",
    13: "Public Administration"
}

pod_23_2["sector_comb"] = pod_23_2["setor1"].map(sector_map)

pod_23_2["sector_comb"] = pod_23_2["sector_comb"].mask(
    pod_23_2["sector_comb"].isna() & pod_23_2["setor1"].notna(),
    "Services"
)

pod_23_2["sector_comb"].value_counts(dropna=False)

sector_comb
NaN                      43538
Services                 43332
Commerce                 13649
Industry                  6690
Construction              3435
Public Administration     2151
Agriculture                117
Name: count, dtype: int64

### Emplyment relationship

In [43]:
pod_23_2["vinc1"].value_counts(dropna=False)

vinc1
NaN    43538
1.0    37493
6.0    10501
5.0     9456
2.0     3640
3.0     3316
4.0     2383
7.0     1290
8.0     1055
9.0      240
Name: count, dtype: int64

In [44]:
empl_map = {
    1: "Wage and salaried employees",
    2: "Wage and salaried employees",
    3: "Public sector",
    5: "Self-employed",
    6: "Self-employed"
}

pod_23_2["empl_relat"] = pod_23_2["vinc1"].map(empl_map)

pod_23_2["empl_relat"] = pod_23_2["empl_relat"].mask(
    pod_23_2["empl_relat"].isna() & pod_23_2["vinc1"].notna(),
    "Other"
)

pod_23_2["empl_relat"].value_counts(dropna=False)

empl_relat
NaN                            43538
Wage and salaried employees    41133
Self-employed                  19957
Other                           4968
Public sector                   3316
Name: count, dtype: int64

### Gender

In [45]:
pod_23_2["sexo"].value_counts(dropna=False)

sexo
2.0    56747
1.0    56123
3.0       42
Name: count, dtype: int64

In [46]:
pod_23_2["gender"] = pod_23_2["sexo"].map({
    1: "Male",
    2: "Female"
})

pod_23_2["gender"].value_counts(dropna=False)

gender
Female    56747
Male      56123
NaN          42
Name: count, dtype: int64

In [47]:
pod_23_2 = pod_23_2[pod_23_2["gender"].notna()].copy()

pod_23_2["gender"].value_counts(dropna=False)

gender
Female    56747
Male      56123
Name: count, dtype: int64

## Adding external data for income per capita in the zone of home address

In [48]:
renda_zona = pd.read_excel(
    "/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2023/pod_23_renda-per-capita_tab06.xlsx"
)

pod_23_2 = pod_23_2.merge(
    renda_zona[["zona", "renda_pc"]],
    on="zona",
    how="left"
).rename(columns={"renda_pc": "pc_income"})

pod_23_2[["zona", "pc_income"]].head()

   zona    pc_income
0   1.0  2309.022764
1   1.0  2309.022764
2   1.0  2309.022764
3   1.0  2309.022764
4   1.0  2309.022764

In [49]:
pod_23_2["pc_income"].isna().sum()

np.int64(0)

### Age intervals

In [50]:
pod_23_2["age"] = pd.cut(
    pod_23_2["idade"],
    bins=[-float("inf"), 15, 29, 59, float("inf")],
    labels=[
        "15 years old or less",
        "16 to 29 years old",
        "30 to 59 years old",
        "60 years old or older"
    ]
)

pod_23_2["age"].value_counts(dropna=False)

age
30 to 59 years old       53588
16 to 29 years old       22793
60 years old or older    18304
15 years old or less     18185
Name: count, dtype: int64

In [51]:
pod_23_2.loc[pod_23_2["idade"] <= 15, "idade"].value_counts(dropna=False).sort_index()

idade
1.0      574
2.0      501
3.0      728
4.0     1024
5.0     1166
6.0     1347
7.0     1270
8.0     1369
9.0     1348
10.0    1440
11.0    1221
12.0    1465
13.0    1495
14.0    1510
15.0    1727
Name: count, dtype: int64

## Creating new dataframe with constructed variables

In [52]:
summary = pd.DataFrame({
    "column": pod_23_2.columns,
    "dtype": pod_23_2.dtypes.values,
    "na_count": pod_23_2.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_23_2[col]) for col in pod_23_2.columns
]

summary.style.set_properties(**{"text-align": "left"})

In [53]:
pod_23_3 = pod_23_2[
    [
        "id_ordem",
        "zona",
        "modoprin_y",
        "distancia",
        "age",
        "gender",
        "grau_ins",
        "renda_fa",
        "pc_income",
        "qt_auto",
        "motivo",
        "h_saida_period",
        "dia_sem",
        "curr_work",
        "sector_comb",
        "empl_relat"
    ]
].copy()

In [54]:
pod_23_3.shape

(112870, 16)

In [55]:
pod_23_3.head()

,id_ordem,zona,modoprin_y,distancia,age,gender,grau_ins,renda_fa,pc_income,qt_auto,motivo,h_saida_period,dia_sem,curr_work,sector_comb,empl_relat
0,1.0,1.0,1,1518.600013,60 years old or older,Male,Upper Secondary Completed / Higher Education I...,7000.0,2309.022764,1.0,Home - Work,Lunch,Tuesday,0,Services,Self-employed
1,2.0,1.0,1,1518.600013,60 years old or older,Male,Upper Secondary Completed / Higher Education I...,7000.0,2309.022764,1.0,Home - Work,Afternoon,Tuesday,0,Services,Self-employed
2,3.0,1.0,0,8350.069281,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,10000.0,2309.022764,0.0,Home - Personal Matters,Afternoon,Tuesday,1,Commerce,Self-employed
3,4.0,1.0,0,8350.069281,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,10000.0,2309.022764,0.0,Home - Personal Matters,Night,Tuesday,1,Commerce,Self-employed
4,5.0,1.0,0,10346.375791,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,10000.0,2309.022764,0.0,Home - Personal Matters,Lunch,Tuesday,1,Commerce,Self-employed

In [56]:
summary = pd.DataFrame({
    "column": pod_23_3.columns,
    "dtype": pod_23_3.dtypes.values,
    "na_count": pod_23_3.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_23_3[col]) for col in pod_23_3.columns
]

summary.style.set_properties(**{"text-align": "left"})

### Checking age intervals

In [57]:
pod_23_2["age"].value_counts(dropna=False)

age
30 to 59 years old       53588
16 to 29 years old       22793
60 years old or older    18304
15 years old or less     18185
Name: count, dtype: int64

#### Under 16 and work

In [58]:
pod_23_3[pod_23_3["age"] == "15 years old or less"]["curr_work"].value_counts(dropna=False)

curr_work
0    18132
1       53
Name: count, dtype: int64

### Saving new dataset

In [59]:
pod_23_3.to_parquet("pod_23_3.parquet")