In [1]:
!pip install pyreadstat

Collecting pyreadstat
  Downloading pyreadstat-1.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)
Downloading pyreadstat-1.3.4-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 28.9 MB/s eta 0:00:0000:0100:01
Installing collected packages: pyreadstat
Successfully installed pyreadstat-1.3.4

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pyreadstat

/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2017/pod_17_renda-per-capita_tab06.xlsx
/kaggle/input/datasets/lefcollado/pod-2017/OD_2017_v1.sav

# Loading data

In [3]:
pod_17, meta = pyreadstat.read_sav("/kaggle/input/datasets/lefcollado/pod-2017/OD_2017_v1.sav")
pod_17.shape

(183092, 128)

In [4]:
pod_17.head()

,zona,muni_dom,co_dom_x,co_dom_y,id_dom,f_dom,fe_dom,dom,cd_entre,data,...,modoprin,tipvg,pag_viag,tp_esauto,vl_est,pe_bici,via_bici,tp_esbici,distancia,id_ordem
0,1.0,36.0,333743.0,7394463.0,00010001,1.0,15.416667,1.0,1.0,06092017,...,16.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,639.132224,1.0
1,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,16.0,3.0,NaN,NaN,NaN,1.0,NaN,NaN,639.132224,2.0
2,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,6651.767885,3.0
3,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,4243.298717,4.0
4,1.0,36.0,333743.0,7394463.0,00010001,0.0,15.416667,1.0,1.0,06092017,...,12.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,4557.622187,5.0

In [5]:
type(pod_17)

pandas.core.frame.DataFrame

## Creating dictionary
Creating a list of variables to match the dictionary providaded by Metro

In [6]:
col17 = list(pod_17.columns)
col17_df = pd.DataFrame(col17, columns=["column_name"])
col17_df.to_excel("pod_17_columns.xlsx", index=False)

# First assessment of dataframe

In [7]:
na_df = pod_17.isna().sum().sort_values(ascending=False).to_frame(name="missing_count")

na_df.to_excel("pod_17_tot_NAs.xlsx")

### Creating new dataframe with variables of interest

In [8]:
pod_17_2 = pod_17[
    [
        "id_ordem",
        "fe_via",
        "zona",
        "modoprin",
        "distancia",
        "dia_sem",
        "motivo_o",
        "motivo_d",
        "h_saida",
        "duracao",
        "idade",
        "sexo",
        "grau_ins",
        "qt_auto",
        "cd_ativi",
        "co_ren_i",
        "vl_ren_i",
        "renda_fa",
        "trab1_re",
        "ocup1",
        "setor1",
        "vinc1",
    ]
].copy()

In [9]:
pod_17_2.shape

(183092, 22)

In [10]:
pod_17_2.head()

,id_ordem,fe_via,zona,modoprin,distancia,dia_sem,motivo_o,motivo_d,h_saida,duracao,...,grau_ins,qt_auto,cd_ativi,co_ren_i,vl_ren_i,renda_fa,trab1_re,ocup1,setor1,vinc1
0,1.0,22.132647,1.0,16.0,639.132224,3.0,8.0,3.0,5.0,10.0,...,3.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,13.0,1.0
1,2.0,22.132647,1.0,16.0,639.132224,3.0,3.0,8.0,15.0,10.0,...,3.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,13.0,1.0
2,3.0,18.882487,1.0,1.0,6651.767885,3.0,8.0,3.0,9.0,50.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0
3,4.0,18.882487,1.0,1.0,4243.298717,3.0,3.0,4.0,17.0,60.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0
4,5.0,18.882487,1.0,12.0,4557.622187,3.0,4.0,8.0,22.0,40.0,...,4.0,0.0,1.0,3.0,NaN,2732.57591,2.0,4.0,7.0,2.0

#### NA count in each column

In [11]:
pod_17_2.isna().sum()

id_ordem         0
fe_via       25100
zona             0
modoprin     25100
distancia    25100
dia_sem      25100
motivo_o     25100
motivo_d     25100
h_saida      25100
duracao      25100
idade            0
sexo             0
grau_ins         0
qt_auto       4162
cd_ativi         0
co_ren_i         0
vl_ren_i     68231
renda_fa         0
trab1_re     80374
ocup1        80374
setor1       80374
vinc1        80374
dtype: int64

### New dataframe without NAs in the column 'Main mode of transport'"

In [12]:
pod_17_2 = pod_17_2[pod_17_2["modoprin"].notna()].copy()

In [13]:
pod_17_2.isna().sum()

id_ordem         0
fe_via           0
zona             0
modoprin         0
distancia        0
dia_sem          0
motivo_o         0
motivo_d         0
h_saida          0
duracao          0
idade            0
sexo             0
grau_ins         0
qt_auto       3567
cd_ativi         0
co_ren_i         0
vl_ren_i     60291
renda_fa         0
trab1_re     60784
ocup1        60784
setor1       60784
vinc1        60784
dtype: int64

In [14]:
pod_17_2.shape

(157992, 22)

# Cleaning and formatting specific columns

## Quantity of cars per household

In [15]:
pod_17_2["qt_auto"].value_counts(dropna=False)

qt_auto
1.0    74051
0.0    52206
2.0    23191
3.0     4025
NaN     3567
4.0      804
5.0      122
8.0       24
6.0        2
Name: count, dtype: int64

#### Removing observations with NA

In [16]:
pod_17_2 = pod_17_2[pod_17_2["qt_auto"].notna()].copy()

In [17]:
pod_17_2["qt_auto"].value_counts(dropna=False)

qt_auto
1.0    74051
0.0    52206
2.0    23191
3.0     4025
4.0      804
5.0      122
8.0       24
6.0        2
Name: count, dtype: int64

## Individual income

In [18]:
desc = pod_17_2["vl_ren_i"].describe()
desc["na_count"] = pod_17_2["vl_ren_i"].isna().sum()
desc

count       96194.000000
mean         1778.645799
std          3239.380286
min             0.000000
25%             0.000000
50%           954.000000
75%          2000.000000
max         55000.000000
na_count    58231.000000
Name: vl_ren_i, dtype: float64

In [19]:
pod_17_2.dropna(subset=["setor1"])["vl_ren_i"].isna().sum(), \
pod_17_2.dropna(subset=["setor1"])["vl_ren_i"].eq(0).sum()

(np.int64(48712), np.int64(471))

## Creating target variable

In [20]:
pod_17_2["modoprin"].value_counts(dropna=False)

modoprin
16.0    47255
9.0     36056
4.0     18181
1.0     13796
10.0    12978
8.0      6302
5.0      5475
13.0     2951
2.0      2873
6.0      2742
12.0     2296
15.0     1283
11.0      900
7.0       674
17.0      395
14.0      267
3.0         1
Name: count, dtype: int64

In [21]:
pod_17_2["modoprin_y"] = pod_17_2["modoprin"].isin([15, 16]).astype(int)

In [22]:
pod_17_2["modoprin_y"].value_counts(dropna=False)

modoprin_y
0    105887
1     48538
Name: count, dtype: int64

## Reason for the trip

In [23]:
pod_17_2["motivo_o"].value_counts(dropna=False)

motivo_o
8.0     69776
3.0     26715
4.0     24917
2.0      6709
10.0     5396
1.0      5171
5.0      4411
7.0      3998
6.0      3825
11.0     3208
9.0       299
Name: count, dtype: int64

#### Transform motivo_o and motivo_d into categorical variable with labels

In [24]:
motivo_labels = {
    1: "Trabalho Indústria",
    2: "Trabalho Comércio",
    3: "Trabalho Serviços",
    4: "Escola/Educação",
    5: "Compras",
    6: "Médico/Dentista/Saúde",
    7: "Recreação/Visitas/Lazer",
    8: "Residência",
    9: "Procurar Emprego",
    10: "Assuntos Pessoais",
    11: "Refeição"
}

pod_17_2["motivo_o_cat"] = pd.Categorical(
    pod_17_2["motivo_o"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

In [25]:
pod_17_2["motivo_o_cat"].value_counts(dropna=False)

motivo_o_cat
Residência                 69776
Trabalho Serviços          26715
Escola/Educação            24917
Trabalho Comércio           6709
Assuntos Pessoais           5396
Trabalho Indústria          5171
Compras                     4411
Recreação/Visitas/Lazer     3998
Médico/Dentista/Saúde       3825
Refeição                    3208
Procurar Emprego             299
Name: count, dtype: int64

In [26]:
pod_17_2["motivo_d_cat"] = pd.Categorical(
    pod_17_2["motivo_d"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

In [27]:
pod_17_2["motivo_d_cat"].value_counts(dropna=False)

motivo_d_cat
Residência                 69577
Trabalho Serviços          26766
Escola/Educação            24933
Trabalho Comércio           6712
Assuntos Pessoais           5409
Trabalho Indústria          5185
Compras                     4390
Recreação/Visitas/Lazer     4113
Médico/Dentista/Saúde       3841
Refeição                    3200
Procurar Emprego             299
Name: count, dtype: int64

#### Grouping categories

In [28]:
pod_17_2["motivo_o_group"] = pod_17_2["motivo_o_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [29]:
pod_17_2["motivo_o_group"] = pd.Categorical(
    pod_17_2["motivo_o_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [30]:
pod_17_2["motivo_o_group"].value_counts(dropna=False)

motivo_o_group
Home                69776
Work                38595
Education           24917
Personal Matters    21137
Name: count, dtype: int64

In [31]:
pod_17_2["motivo_d_group"] = pod_17_2["motivo_d_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [32]:
pod_17_2["motivo_d_group"] = pd.Categorical(
    pod_17_2["motivo_d_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [33]:
pod_17_2["motivo_d_group"].value_counts(dropna=False)

motivo_d_group
Home                69577
Work                38663
Education           24933
Personal Matters    21252
Name: count, dtype: int64

In [34]:
pod_17_2["motivo_d_group"].dtype

CategoricalDtype(categories=['Home', 'Work', 'Education', 'Personal Matters'], ordered=False, categories_dtype=object)

#### Join the two columns

In [35]:
# Create the column
pod_17_2["motivo"] = pod_17_2.apply(
    lambda row:
        "Home - Work"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Work"}
        else "Home - Education"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Education"}
        else "Home - Personal Matters"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Personal Matters"}
        else "Others",
    axis=1
)

# Convert to ordered categorical
motivo_order = [
    "Home - Work",
    "Home - Education",
    "Home - Personal Matters",
    "Others"
]

pod_17_2["motivo"] = pd.Categorical(
    pod_17_2["motivo"],
    categories=motivo_order,
    ordered=True
)

# Check counts (now respects category order if sorted)
pod_17_2["motivo"].value_counts(dropna=False).sort_index()

motivo
Home - Work                64402
Home - Education           45105
Home - Personal Matters    29846
Others                     15072
Name: count, dtype: int64

## Level of education

In [36]:
grau_labels = {
    1: "No Formal Education/Incomplete Primary Education",
    2: "Primary Education Completed / Lower Secondary Incomplete",
    3: "Lower Secondary Completed / Upper Secondary Incomplete",
    4: "Upper Secondary Completed / Higher Education Incomplete",
    5: "Higher Education Completed"
}

pod_17_2["grau_ins"] = pd.Categorical(
    pod_17_2["grau_ins"].map(grau_labels),
    categories=list(grau_labels.values()),
    ordered=True
)

In [37]:
pod_17_2["grau_ins"].value_counts(dropna=False)

grau_ins
Upper Secondary Completed / Higher Education Incomplete     50627
Higher Education Completed                                  46408
No Formal Education/Incomplete Primary Education            21193
Lower Secondary Completed / Upper Secondary Incomplete      18827
Primary Education Completed / Lower Secondary Incomplete    17370
Name: count, dtype: int64

## Currently working on a steady job?

In [38]:
pod_17_2["cd_ativi"].value_counts(dropna=False)

cd_ativi
1.0    87448
8.0    27583
4.0    12212
5.0     8216
2.0     7059
7.0     6455
6.0     5059
3.0      393
Name: count, dtype: int64

In [39]:
pod_17_2["curr_work"] = (pod_17_2["cd_ativi"] == 1).astype(int)
pod_17_2["curr_work"].value_counts(dropna=False)

curr_work
1    87448
0    66977
Name: count, dtype: int64

## Days of the week

In [40]:
pod_17_2["dia_sem"].value_counts(dropna=False)

dia_sem
6.0    56545
5.0    28636
3.0    27533
4.0    24378
2.0    17333
Name: count, dtype: int64

In [41]:
day_labels = {
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}

pod_17_2["dia_sem"] = pd.Categorical(
    pod_17_2["dia_sem"].map(day_labels),
    categories=list(day_labels.values()),
    ordered=True
)

pod_17_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       56545
Thursday     28636
Tuesday      27533
Wednesday    24378
Monday       17333
Name: count, dtype: int64

## Time of day of trip start

In [42]:
pod_17_2["h_saida"].dtype

dtype('float64')

In [43]:
pod_17_2["h_saida"].head()

0     5.0
1    15.0
2     9.0
3    17.0
4    22.0
Name: h_saida, dtype: float64

In [44]:
pod_17_2["h_saida"].describe()

count    154425.000000
mean         12.739563
std           4.862124
min           0.000000
25%           8.000000
50%          12.000000
75%          17.000000
max          23.000000
Name: h_saida, dtype: float64

In [45]:
pod_17_2["h_saida_period"] = pd.cut(
    pod_17_2["h_saida"],
    bins=[0, 5, 10, 13, 18, 24],
    labels=["Dawn", "Morning", "Lunch", "Afternoon", "Night"],
    include_lowest=True,
    right=True
)

pod_17_2["h_saida_period"].value_counts(dropna=False)

h_saida_period
Afternoon    49302
Morning      46280
Lunch        37276
Night        16467
Dawn          5100
Name: count, dtype: int64

## In which sector is your main occupation?

In [46]:
pod_17_2["setor1"].value_counts(dropna=False)

setor1
NaN     59539
14.0    19769
4.0     16782
12.0    11585
3.0      9280
11.0     6921
10.0     6825
9.0      4734
2.0      4171
13.0     3544
7.0      3530
8.0      2971
6.0      2789
5.0      1786
1.0       199
Name: count, dtype: int64

In [47]:
sector_map = {
    1: "Agriculture",
    2: "Construction",
    3: "Industry",
    4: "Commerce",
    13: "Public Administration"
}

# Map values
pod_17_2["sector_comb"] = pod_17_2["setor1"].map(sector_map)

# Fill remaining non-null setor1 values as "Services"
pod_17_2["sector_comb"] = pod_17_2["sector_comb"].mask(
    pod_17_2["sector_comb"].isna() & pod_17_2["setor1"].notna(),
    "Services"
)

# Define desired order
sector_order = [
    "Services",
    "Commerce",
    "Industry",
    "Construction",
    "Public Administration",
    "Agriculture"
]

# Convert to ordered categorical
pod_17_2["sector_comb"] = pd.Categorical(
    pod_17_2["sector_comb"],
    categories=sector_order,
    ordered=True
)

# Check counts in correct order
pod_17_2["sector_comb"].value_counts(dropna=False).sort_index()

sector_comb
Services                 60910
Commerce                 16782
Industry                  9280
Construction              4171
Public Administration     3544
Agriculture                199
NaN                      59539
Name: count, dtype: int64

## Emplyment relationship

In [48]:
pod_17_2["vinc1"].value_counts(dropna=False)

vinc1
NaN    59539
1.0    47856
4.0    19983
2.0     6107
6.0     6025
3.0     5323
7.0     5239
5.0     3938
8.0      415
Name: count, dtype: int64

In [49]:
empl_map = {
    1: "Wage and salaried employees",
    2: "Wage and salaried employees",
    3: "Public sector",
    4: "Self-employed"
}

# Map values
pod_17_2["empl_relat"] = pod_17_2["vinc1"].map(empl_map)

# Fill remaining non-null vinc1 values as "Other"
pod_17_2["empl_relat"] = pod_17_2["empl_relat"].mask(
    pod_17_2["empl_relat"].isna() & pod_17_2["vinc1"].notna(),
    "Other"
)

# Define desired order
empl_order = [
    "Wage and salaried employees",
    "Self-employed",
    "Public sector",
    "Other"
]

# Convert to ordered categorical
pod_17_2["empl_relat"] = pd.Categorical(
    pod_17_2["empl_relat"],
    categories=empl_order,
    ordered=True
)

# Check counts in correct order
pod_17_2["empl_relat"].value_counts(dropna=False).sort_index()

empl_relat
Wage and salaried employees    53963
Self-employed                  19983
Public sector                   5323
Other                          15617
NaN                            59539
Name: count, dtype: int64

## Gender

In [50]:
pod_17_2["gender"] = pod_17_2["sexo"].map({
    1: "Male",
    2: "Female"
})

pod_17_2["gender"].value_counts(dropna=False)

gender
Male      77306
Female    77119
Name: count, dtype: int64

## Age intervals

#### Keeping only 16 year-olds and older

In [51]:
pod_17_2 = pod_17_2[pod_17_2["idade"] >= 16]

#### Creating categories

In [52]:
pod_17_2["age"] = pd.cut(
    pod_17_2["idade"],
    bins=[-float("inf"), 29, 59, float("inf")],
    labels=[
        "16 to 29 years old",
        "30 to 59 years old",
        "60 years old or older"
    ]
)

pod_17_2["age"].value_counts(dropna=False)

age
30 to 59 years old       74716
16 to 29 years old       32766
60 years old or older    21775
Name: count, dtype: int64

In [53]:
pod_17_2.loc[pod_17_2["idade"] <= 15, "idade"].value_counts(dropna=False).sort_index()

Series([], Name: count, dtype: int64)

## Distance travelled
Log

In [54]:
pod_17_2["distancia"].describe()

count    129257.000000
mean       5567.483899
std        7091.561995
min           1.000000
25%         794.783618
50%        2792.021669
75%        7563.271580
max       82753.551253
Name: distancia, dtype: float64

In [55]:
pod_17_2["dist_log"] = np.log1p(pod_17_2["distancia"])
pod_17_2["dist_log"].describe()

count    129257.000000
mean          7.725019
std           1.581658
min           0.693147
25%           6.679327
50%           7.934879
75%           8.931191
max          11.323634
Name: dist_log, dtype: float64

## Monthly family income
Log

In [56]:
pod_17_2["renda_fa"].describe()

count    129257.000000
mean       5855.620736
std        5730.331090
min           0.000000
25%        2588.930150
50%        4000.000000
75%        6843.126522
max      100000.000000
Name: renda_fa, dtype: float64

In [57]:
pod_17_2["fam_inc_log"] = np.log1p(pod_17_2["renda_fa"])
pod_17_2["fam_inc_log"].describe()

count    129257.000000
mean          8.322524
std           0.996798
min           0.000000
25%           7.859386
50%           8.294300
75%           8.831146
max          11.512935
Name: fam_inc_log, dtype: float64

# Adding external data for income per capita in the zone of home address

In [58]:
renda_zona = pd.read_excel(
    "/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2017/pod_17_renda-per-capita_tab06.xlsx"
)

pod_17_2 = pod_17_2.merge(
    renda_zona[["zona", "renda_pc"]],
    on="zona",
    how="left"
).rename(columns={"renda_pc": "pc_income"})

pod_17_2[["zona", "pc_income"]].head()

   zona    pc_income
0   1.0  1151.811909
1   1.0  1151.811909
2   1.0  1151.811909
3   1.0  1151.811909
4   1.0  1151.811909

In [59]:
pod_17_2["pc_income"].isna().sum()

np.int64(0)

#### In log

In [60]:
pod_17_2["pc_income"].describe()

count    129257.000000
mean       1761.880617
std        1084.874404
min         555.574344
25%         914.843988
50%        1261.262334
75%        2480.665974
max        5568.666490
Name: pc_income, dtype: float64

In [61]:
pod_17_2["pc_inc_log"] = np.log1p(pod_17_2["pc_income"])
pod_17_2["pc_inc_log"].describe()

count    129257.000000
mean          7.308428
std           0.561070
min           6.321801
25%           6.819846
50%           7.140661
75%           7.816685
max           8.625090
Name: pc_inc_log, dtype: float64

# Creating new dataframe with constructed variables

In [62]:
summary = pd.DataFrame({
    "column": pod_17_2.columns,
    "dtype": pod_17_2.dtypes.values,
    "na_count": pod_17_2.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_17_2[col]) for col in pod_17_2.columns
]

summary.style.set_properties(**{"text-align": "left"})

In [63]:
pod_17_3 = pod_17_2[
    [
        "id_ordem",
        "fe_via",
        "zona",
        "modoprin_y",
        "dist_log",
        "age",
        "gender",
        "grau_ins",
        "fam_inc_log",
        "pc_inc_log",
        "qt_auto",
        "motivo",
        "h_saida_period",
        "dia_sem",
        "curr_work",
        "sector_comb",
        "empl_relat"
    ]
].copy()

In [64]:
pod_17_3.shape

(129257, 17)

In [65]:
pod_17_3.head()

,id_ordem,fe_via,zona,modoprin_y,dist_log,age,gender,grau_ins,fam_inc_log,pc_inc_log,qt_auto,motivo,h_saida_period,dia_sem,curr_work,sector_comb,empl_relat
0,1.0,22.132647,1.0,1,6.461675,30 to 59 years old,Female,Lower Secondary Completed / Upper Secondary In...,7.913366,7.049959,0.0,Home - Work,Dawn,Tuesday,1,Public Administration,Wage and salaried employees
1,2.0,22.132647,1.0,1,6.461675,30 to 59 years old,Female,Lower Secondary Completed / Upper Secondary In...,7.913366,7.049959,0.0,Home - Work,Afternoon,Tuesday,1,Public Administration,Wage and salaried employees
2,3.0,18.882487,1.0,0,8.802788,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,7.913366,7.049959,0.0,Home - Work,Morning,Tuesday,1,Services,Wage and salaried employees
3,4.0,18.882487,1.0,0,8.353332,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,7.913366,7.049959,0.0,Others,Afternoon,Tuesday,1,Services,Wage and salaried employees
4,5.0,18.882487,1.0,0,8.424776,16 to 29 years old,Female,Upper Secondary Completed / Higher Education I...,7.913366,7.049959,0.0,Home - Education,Night,Tuesday,1,Services,Wage and salaried employees

In [66]:
summary = pd.DataFrame({
    "column": pod_17_3.columns,
    "dtype": pod_17_3.dtypes.values,
    "na_count": pod_17_3.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_17_3[col]) for col in pod_17_3.columns
]

summary.style.set_properties(**{"text-align": "left"})

# Saving new dataset

## Full dataset

In [67]:
pod_17_3.to_parquet("pod_17_3_full.parquet")

In [68]:
pod_17_3.shape

(129257, 17)

## Without work info

In [69]:
pod_17_3.drop(columns=["sector_comb", "empl_relat"]).shape

(129257, 15)

In [70]:
pod_17_3.drop(columns=["sector_comb", "empl_relat"]).to_parquet("pod_17_3_no-work-info.parquet")

## Only observations with work info

In [71]:
pod_17_3.loc[pod_17_3["sector_comb"].notna(), "empl_relat"].isna().sum()

np.int64(0)

In [72]:
pod_17_3.loc[pod_17_3["empl_relat"].notna(), "sector_comb"].isna().sum()

np.int64(0)

In [73]:
pod_17_3[pod_17_3["sector_comb"].notna()] \
    .shape

(94756, 17)

In [74]:
#pod_17_3[pod_17_3["sector_comb"].notna()] \
#    .reset_index(drop=True) \
#    .to_parquet("pod_17_3_workers.parquet")

pod_17_3[pod_17_3["sector_comb"].notna()] \
    .drop(columns=["curr_work"]) \
    .reset_index(drop=True) \
    .to_parquet("pod_17_3_workers.parquet")