In [73]:
!pip install pyreadstat

Requirement already satisfied: pyreadstat in /usr/local/lib/python3.12/dist-packages (1.3.4)
Requirement already satisfied: narwhals>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from pyreadstat) (2.0.2)

In [74]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

import pyreadstat

/kaggle/input/datasets/lefcollado/pod-2023/Banco2023_divulgacao_190225.sav
/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2023/pod_23_renda-per-capita_tab06.xlsx

# Loading data

In [75]:
pod_23, meta = pyreadstat.read_sav("/kaggle/input/datasets/lefcollado/pod-2023/Banco2023_divulgacao_190225.sav")
pod_23.shape

(143038, 147)

In [76]:
pod_23.head()

,zona,muni_dom,co_dom_x,co_dom_y,id_dom,f_dom,Fe_dom,dom,cd_entre,DATA,...,duracao,modoprin,tipvg,tp_esauto,vl_est,pe_bici,tp_estbici,prop_bici,distancia,id_ordem
0,1.0,36.0,333725.0,7394554.0,,1.0,32.34,1.0,1.0,2024-04-17,...,30.0,16.0,4.0,NaN,NaN,7.0,2.0,1.0,1518.600013,1.0
1,1.0,36.0,333725.0,7394554.0,00100001,0.0,32.34,1.0,1.0,2024-04-17,...,30.0,16.0,4.0,NaN,NaN,9.0,2.0,1.0,1518.600013,2.0
2,1.0,36.0,333725.0,7394554.0,00100002,1.0,32.34,2.0,1.0,2024-04-17,...,30.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,8350.069281,3.0
3,1.0,36.0,333725.0,7394554.0,00100002,0.0,32.34,2.0,1.0,2024-04-17,...,25.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,8350.069281,4.0
4,1.0,36.0,333725.0,7394554.0,00100002,0.0,32.34,2.0,1.0,2024-04-17,...,30.0,12.0,2.0,NaN,NaN,NaN,NaN,NaN,10346.375791,5.0

In [77]:
type(pod_23)

pandas.core.frame.DataFrame

## Creating dictionary
Creating a list of variables to match the dictionary providaded by Metro

In [78]:
col23 = list(pod_23.columns)
col23_df = pd.DataFrame(col23, columns=["column_name"])
col23_df.to_excel("pod_23_columns.xlsx", index=False)

# First assessment of dataframe

In [79]:
na_df = pod_23.isna().sum().sort_values(ascending=False).to_frame(name="missing_count")

na_df.to_excel("pod_23_tot_NAs.xlsx")

### Creating new dataframe with variables of interest

In [80]:
pod_23_2 = pod_23[
    [
        "id_ordem",
        "Fe_via",
        "zona",
        "modoprin",
        "distancia",
        "dia_sem",
        "motivo_o",
        "motivo_d",
        "h_saida",
        "idade",
        "sexo",
        "grau_ins",
        "qt_auto",
        "cd_ativi",
        "renda_fa",
        "setor1",
        "vinc1",
    ]
].copy()

In [81]:
pod_23_2.shape

(143038, 17)

In [82]:
pod_23_2.head()

,id_ordem,Fe_via,zona,modoprin,distancia,dia_sem,motivo_o,motivo_d,h_saida,idade,sexo,grau_ins,qt_auto,cd_ativi,renda_fa,setor1,vinc1
0,1.0,51.023290,1.0,16.0,1518.600013,3.0,8.0,2.0,11.0,67.0,1.0,4.0,1.0,4.0,7000.0,9.0,6.0
1,2.0,51.023290,1.0,16.0,1518.600013,3.0,2.0,8.0,15.0,67.0,1.0,4.0,1.0,4.0,7000.0,9.0,6.0
2,3.0,21.972599,1.0,12.0,8350.069281,3.0,8.0,7.0,18.0,22.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0
3,4.0,21.972599,1.0,12.0,8350.069281,3.0,7.0,8.0,23.0,22.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0
4,5.0,21.972599,1.0,12.0,10346.375791,3.0,8.0,7.0,13.0,21.0,2.0,3.0,0.0,1.0,10000.0,4.0,6.0

#### NA count in each column

In [83]:
pod_23_2.isna().sum()

id_ordem         0
Fe_via           0
zona             0
modoprin     30125
distancia    30125
dia_sem      30125
motivo_o     30125
motivo_d     30125
h_saida      30125
idade            0
sexo             0
grau_ins         0
qt_auto        179
cd_ativi         0
renda_fa         0
setor1       63696
vinc1        63696
dtype: int64

### New dataframe without NAs in the column 'Main mode of transport'"

In [84]:
pod_23_2 = pod_23_2[pod_23_2["modoprin"].notna()].copy()

In [85]:
pod_23_2.isna().sum()

id_ordem         0
Fe_via           0
zona             0
modoprin         0
distancia        0
dia_sem          0
motivo_o         0
motivo_d         0
h_saida          0
idade            0
sexo             0
grau_ins         0
qt_auto        110
cd_ativi         0
renda_fa         0
setor1       43538
vinc1        43538
dtype: int64

In [86]:
pod_23_2.shape

(112913, 17)

# Cleaning and formatting specific columns

## Quantity of cars per household

In [87]:
pod_23_2["qt_auto"].value_counts(dropna=False)

qt_auto
1.0    55889
0.0    39476
2.0    14721
3.0     2229
4.0      415
NaN      110
5.0       37
9.0       22
6.0       14
Name: count, dtype: int64

#### Removing observations with NA

In [88]:
pod_23_2 = pod_23_2[pod_23_2["qt_auto"].notna()].copy()

## Creating target variable

In [89]:
pod_23_2["modoprin"].value_counts(dropna=False)

modoprin
17.0    29945
9.0     27738
4.0     12466
1.0      9348
10.0     8558
8.0      5925
12.0     4229
6.0      3834
13.0     3013
5.0      2492
2.0      2470
16.0      970
7.0       741
11.0      485
14.0      276
18.0      208
3.0        81
15.0       24
Name: count, dtype: int64

In [90]:
pod_23_2["modoprin_y"] = pod_23_2["modoprin"].isin([16, 17]).astype(int)

In [91]:
pod_23_2["modoprin_y"].value_counts(dropna=False)

modoprin_y
0    81888
1    30915
Name: count, dtype: int64

## Reason for the trip

In [92]:
pod_23_2["motivo_o"].value_counts(dropna=False)

motivo_o
8.0     54035
3.0     18722
4.0     18069
2.0      5263
1.0      3415
5.0      3204
6.0      3168
10.0     3117
7.0      2759
11.0      954
9.0        97
Name: count, dtype: int64

Transform motivo_o and motivo_d into categorical variable with labels

In [93]:
motivo_labels = {
    1: "Trabalho Indústria",
    2: "Trabalho Comércio",
    3: "Trabalho Serviços",
    4: "Escola/Educação",
    5: "Compras",
    6: "Médico/Dentista/Saúde",
    7: "Recreação/Visitas/Lazer",
    8: "Residência",
    9: "Procurar Emprego",
    10: "Assuntos Pessoais",
    11: "Refeição"
}

pod_23_2["motivo_o_cat"] = pd.Categorical(
    pod_23_2["motivo_o"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

pod_23_2["motivo_o_cat"].value_counts(dropna=False)

motivo_o_cat
Residência                 54035
Trabalho Serviços          18722
Escola/Educação            18069
Trabalho Comércio           5263
Trabalho Indústria          3415
Compras                     3204
Médico/Dentista/Saúde       3168
Assuntos Pessoais           3117
Recreação/Visitas/Lazer     2759
Refeição                     954
Procurar Emprego              97
Name: count, dtype: int64

In [94]:
pod_23_2["motivo_d_cat"] = pd.Categorical(
    pod_23_2["motivo_d"].map(motivo_labels),
    categories=list(motivo_labels.values())
)

pod_23_2["motivo_d_cat"].value_counts()

motivo_d_cat
Residência                 53785
Trabalho Serviços          18809
Escola/Educação            18103
Trabalho Comércio           5283
Trabalho Indústria          3509
Compras                     3208
Médico/Dentista/Saúde       3167
Assuntos Pessoais           3044
Recreação/Visitas/Lazer     2854
Refeição                     943
Procurar Emprego              98
Name: count, dtype: int64

#### Grouping categories

In [95]:
pod_23_2["motivo_o_group"] = pod_23_2["motivo_o_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [96]:
pod_23_2["motivo_o_group"] = pd.Categorical(
    pod_23_2["motivo_o_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [97]:
pod_23_2["motivo_o_group"].value_counts(dropna=False)

motivo_o_group
Home                54035
Work                27400
Education           18069
Personal Matters    13299
Name: count, dtype: int64

In [98]:
pod_23_2["motivo_d_group"] = pod_23_2["motivo_d_cat"].map({
    "Residência": "Home",
    
    "Trabalho Serviços": "Work",
    "Trabalho Comércio": "Work",
    "Trabalho Indústria": "Work",
    
    "Escola/Educação": "Education",
    
    "Assuntos Pessoais": "Personal Matters",
    "Compras": "Personal Matters",
    "Refeição": "Personal Matters",
    "Procurar Emprego": "Personal Matters",
    "Recreação/Visitas/Lazer": "Personal Matters",
    "Médico/Dentista/Saúde": "Personal Matters"
})

In [99]:
pod_23_2["motivo_d_group"] = pd.Categorical(
    pod_23_2["motivo_d_group"],
    categories=["Home", "Work", "Education", "Personal Matters"]
)

In [100]:
pod_23_2["motivo_d_group"].value_counts()

motivo_d_group
Home                53785
Work                27601
Education           18103
Personal Matters    13314
Name: count, dtype: int64

In [101]:
pod_23_2["motivo_d_group"].dtype

CategoricalDtype(categories=['Home', 'Work', 'Education', 'Personal Matters'], ordered=False, categories_dtype=object)

#### Join the two columns

In [102]:
# Create the column
pod_23_2["motivo"] = pod_23_2.apply(
    lambda row:
        "Home - Work"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Work"}
        else "Home - Education"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Education"}
        else "Home - Personal Matters"
        if {str(row["motivo_o_group"]), str(row["motivo_d_group"])} == {"Home", "Personal Matters"}
        else "Others",
    axis=1
)

# Convert to ordered categorical
motivo_order = [
    "Home - Work",
    "Home - Education",
    "Home - Personal Matters",
    "Others"
]

pod_23_2["motivo"] = pd.Categorical(
    pod_23_2["motivo"],
    categories=motivo_order,
    ordered=True
)

# Check counts (now respects category order if sorted)
pod_23_2["motivo"].value_counts(dropna=False).sort_index()

motivo
Home - Work                50902
Home - Education           34037
Home - Personal Matters    22881
Others                      4983
Name: count, dtype: int64

## Level of education

In [103]:
grau_labels = {
    1: "No Formal Education/Incomplete Primary Education",
    2: "Primary Education Completed / Lower Secondary Incomplete",
    3: "Lower Secondary Completed / Upper Secondary Incomplete",
    4: "Upper Secondary Completed / Higher Education Incomplete",
    5: "Higher Education Completed"
}

pod_23_2["grau_ins"] = pd.Categorical(
    pod_23_2["grau_ins"].map(grau_labels),
    categories=list(grau_labels.values()),
    ordered=True
)

pod_23_2["grau_ins"].value_counts()

grau_ins
Upper Secondary Completed / Higher Education Incomplete     38009
Higher Education Completed                                  34945
No Formal Education/Incomplete Primary Education            14197
Lower Secondary Completed / Upper Secondary Incomplete      13426
Primary Education Completed / Lower Secondary Incomplete    12226
Name: count, dtype: int64

## Currently working on a steady job?

In [104]:
pod_23_2["cd_ativi"].value_counts(dropna=False)

cd_ativi
1.0    66174
8.0    20006
4.0    11000
5.0     4936
7.0     4039
6.0     3812
2.0     2648
3.0      188
Name: count, dtype: int64

In [105]:
pod_23_2["curr_work"] = (pod_23_2["cd_ativi"] == 1).astype(int)
pod_23_2["curr_work"].value_counts()

curr_work
1    66174
0    46629
Name: count, dtype: int64

## Days of the week

In [106]:
pod_23_2["dia_sem"].value_counts()

dia_sem
6.0    34087
3.0    26785
2.0    20789
4.0    16335
5.0    14806
0.0        1
Name: count, dtype: int64

In [107]:
day_labels = {
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}

pod_23_2["dia_sem"] = pd.Categorical(
    pod_23_2["dia_sem"].map(day_labels),
    categories=list(day_labels.values()),
    ordered=True
)

pod_23_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       34087
Tuesday      26785
Monday       20789
Wednesday    16335
Thursday     14806
NaN              1
Name: count, dtype: int64

In [108]:
pod_23_2 = pod_23_2[pod_23_2["dia_sem"].notna()].copy()

In [109]:
pod_23_2["dia_sem"].value_counts(dropna=False)

dia_sem
Friday       34087
Tuesday      26785
Monday       20789
Wednesday    16335
Thursday     14806
Name: count, dtype: int64

## Time of day of trip start

In [110]:
pod_23_2["h_saida"].dtype

dtype('float64')

In [111]:
pod_23_2["h_saida"].head()

0    11.0
1    15.0
2    18.0
3    23.0
4    13.0
Name: h_saida, dtype: float64

In [112]:
pod_23_2["h_saida"].describe()

count    112802.000000
mean         12.444354
std           4.926980
min           0.000000
25%           8.000000
50%          12.000000
75%          17.000000
max          23.000000
Name: h_saida, dtype: float64

In [113]:
pod_23_2["h_saida_period"] = pd.cut(
    pod_23_2["h_saida"],
    bins=[0, 5, 10, 13, 18, 24],
    labels=["Dawn", "Morning", "Lunch", "Afternoon", "Night"],
    include_lowest=True,
    right=True
)

pod_23_2["h_saida_period"].value_counts()

h_saida_period
Morning      37665
Afternoon    36353
Lunch        23760
Night        10800
Dawn          4224
Name: count, dtype: int64

## In which sector is your main occupation?

In [114]:
pod_23_2["setor1"].value_counts(dropna=False)

setor1
NaN     43500
4.0     13641
14.0    10917
12.0    10133
3.0      6684
10.0     6480
11.0     4874
2.0      3431
9.0      2902
8.0      2310
7.0      2201
13.0     2145
6.0      1838
5.0      1629
1.0       117
Name: count, dtype: int64

In [115]:
sector_map = {
    1: "Agriculture",
    2: "Construction",
    3: "Industry",
    4: "Commerce",
    13: "Public Administration"
}

# Map values
pod_23_2["sector_comb"] = pod_23_2["setor1"].map(sector_map)

# Fill remaining non-null setor1 values as "Services"
pod_23_2["sector_comb"] = pod_23_2["sector_comb"].mask(
    pod_23_2["sector_comb"].isna() & pod_23_2["setor1"].notna(),
    "Services"
)

# Define desired order
sector_order = [
    "Services",
    "Commerce",
    "Industry",
    "Construction",
    "Public Administration",
    "Agriculture"
]

# Convert to ordered categorical
pod_23_2["sector_comb"] = pd.Categorical(
    pod_23_2["sector_comb"],
    categories=sector_order,
    ordered=True
)

# Check counts in correct order
pod_23_2["sector_comb"].value_counts(dropna=False).sort_index()

sector_comb
NaN                      43500
Services                 43284
Commerce                 13641
Industry                  6684
Construction              3431
Public Administration     2145
Agriculture                117
Name: count, dtype: int64

## Emplyment relationship

In [116]:
pod_23_2["vinc1"].value_counts(dropna=False)

vinc1
NaN    43500
1.0    37458
6.0    10483
5.0     9447
2.0     3638
3.0     3310
4.0     2381
7.0     1290
8.0     1055
9.0      240
Name: count, dtype: int64

In [117]:
empl_map = {
    1: "Wage and salaried employees",
    2: "Wage and salaried employees",
    3: "Public sector",
    5: "Self-employed",
    6: "Self-employed"
}

# Map values
pod_23_2["empl_relat"] = pod_23_2["vinc1"].map(empl_map)

# Fill remaining non-null vinc1 values as "Other"
pod_23_2["empl_relat"] = pod_23_2["empl_relat"].mask(
    pod_23_2["empl_relat"].isna() & pod_23_2["vinc1"].notna(),
    "Other"
)

# Define desired order
empl_order = [
    "Wage and salaried employees",
    "Self-employed",
    "Public sector",
    "Other"
]

# Convert to ordered categorical
pod_23_2["empl_relat"] = pd.Categorical(
    pod_23_2["empl_relat"],
    categories=empl_order,
    ordered=True
)

# Check counts in correct order
pod_23_2["empl_relat"].value_counts(dropna=False).sort_index()

empl_relat
Wage and salaried employees    41096
Self-employed                  19930
Public sector                   3310
Other                           4966
NaN                            43500
Name: count, dtype: int64

## Gender

In [118]:
pod_23_2["sexo"].value_counts(dropna=False)

sexo
2.0    56691
1.0    56069
3.0       42
Name: count, dtype: int64

In [119]:
pod_23_2["gender"] = pod_23_2["sexo"].map({
    1: "Male",
    2: "Female"
})

pod_23_2["gender"].value_counts(dropna=False)

gender
Female    56691
Male      56069
NaN          42
Name: count, dtype: int64

In [120]:
pod_23_2 = pod_23_2[pod_23_2["gender"].notna()].copy()

pod_23_2["gender"].value_counts(dropna=False)

gender
Female    56691
Male      56069
Name: count, dtype: int64

## Age intervals

#### Keeping only 16 year-olds and older

In [121]:
pod_23_2 = pod_23_2[pod_23_2["idade"] >= 16]

#### Creating categories

In [122]:
pod_23_2["age"] = pd.cut(
    pod_23_2["idade"],
    bins=[-float("inf"), 29, 59, float("inf")],
    labels=[
        "16 to 29 years old",
        "30 to 59 years old",
        "60 years old or older"
    ]
)

pod_23_2["age"].value_counts(dropna=False)

age
30 to 59 years old       53529
16 to 29 years old       22774
60 years old or older    18286
Name: count, dtype: int64

In [123]:
pod_23_2.loc[pod_23_2["idade"] <= 15, "idade"].value_counts(dropna=False).sort_index()

Series([], Name: count, dtype: int64)

## Distance travelled
Log

In [124]:
pod_23_2["distancia"].describe()

count    94589.000000
mean      6012.581809
std       7493.141598
min          0.000000
25%        975.201005
50%       3148.369896
75%       8132.619381
max      96896.122590
Name: distancia, dtype: float64

In [125]:
pod_23_2["dist_log"] = np.log1p(pod_23_2["distancia"])
pod_23_2["dist_log"].describe()

count    94589.000000
mean         7.885396
std          1.467938
min          0.000000
25%          6.883669
50%          8.054958
75%          9.003761
max         11.481405
Name: dist_log, dtype: float64

## Monthly family income
Log

In [126]:
pod_23_2["renda_fa"].describe()

count     94589.000000
mean       9841.492741
std       13726.017943
min           0.000000
25%        3797.126973
50%        6000.000000
75%       10850.864140
max      704000.000000
Name: renda_fa, dtype: float64

In [127]:
pod_23_2["fam_inc_log"] = np.log1p(pod_23_2["renda_fa"])
pod_23_2["fam_inc_log"].describe()

count    94589.000000
mean         8.756302
std          1.006025
min          0.000000
25%          8.242263
50%          8.699681
75%          9.292092
max         13.464535
Name: fam_inc_log, dtype: float64

# Adding external data for income per capita in the zone of home address

In [128]:
renda_zona = pd.read_excel(
    "/kaggle/input/datasets/lefcollado/renda-per-capita-por-zona-od-2023/pod_23_renda-per-capita_tab06.xlsx"
)

pod_23_2 = pod_23_2.merge(
    renda_zona[["zona", "renda_pc"]],
    on="zona",
    how="left"
).rename(columns={"renda_pc": "pc_income"})

pod_23_2[["zona", "pc_income"]].head()

   zona    pc_income
0   1.0  2309.022764
1   1.0  2309.022764
2   1.0  2309.022764
3   1.0  2309.022764
4   1.0  2309.022764

In [129]:
pod_23_2["pc_income"].isna().sum()

np.int64(0)

#### In log

In [130]:
pod_23_2["pc_income"].describe()

count    94589.000000
mean      3455.262615
std       2929.906437
min        954.666698
25%       1590.238804
50%       2270.051531
75%       4399.594935
max      23265.236388
Name: pc_income, dtype: float64

In [131]:
pod_23_2["pc_inc_log"] = np.log1p(pod_23_2["pc_income"])
pod_23_2["pc_inc_log"].describe()

count    94589.000000
mean         7.904899
std          0.652597
min          6.862409
25%          7.372268
50%          7.727998
75%          8.389495
max         10.054759
Name: pc_inc_log, dtype: float64

# Creating new dataframe with constructed variables

In [132]:
summary = pd.DataFrame({
    "column": pod_23_2.columns,
    "dtype": pod_23_2.dtypes.values,
    "na_count": pod_23_2.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_23_2[col]) for col in pod_23_2.columns
]

summary.style.set_properties(**{"text-align": "left"})

In [133]:
pod_23_3 = pod_23_2[
    [
        "id_ordem",
        "Fe_via",
        "zona",
        "modoprin_y",
        "dist_log",
        "age",
        "gender",
        "grau_ins",
        "fam_inc_log",
        "pc_inc_log",
        "qt_auto",
        "motivo",
        "h_saida_period",
        "dia_sem",
        "curr_work",
        "sector_comb",
        "empl_relat"
    ]
].copy()

In [134]:
pod_23_3.shape

(94589, 17)

In [135]:
pod_23_3.head()

,id_ordem,Fe_via,zona,modoprin_y,dist_log,age,gender,grau_ins,fam_inc_log,pc_inc_log,qt_auto,motivo,h_saida_period,dia_sem,curr_work,sector_comb,empl_relat
0,1.0,51.023290,1.0,1,7.326202,60 years old or older,Male,Upper Secondary Completed / Higher Education I...,8.853808,7.745013,1.0,Home - Work,Lunch,Tuesday,0,Services,Self-employed
1,2.0,51.023290,1.0,1,7.326202,60 years old or older,Male,Upper Secondary Completed / Higher Education I...,8.853808,7.745013,1.0,Home - Work,Afternoon,Tuesday,0,Services,Self-employed
2,3.0,21.972599,1.0,0,9.030145,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,9.210440,7.745013,0.0,Home - Personal Matters,Afternoon,Tuesday,1,Commerce,Self-employed
3,4.0,21.972599,1.0,0,9.030145,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,9.210440,7.745013,0.0,Home - Personal Matters,Night,Tuesday,1,Commerce,Self-employed
4,5.0,21.972599,1.0,0,9.244488,16 to 29 years old,Female,Lower Secondary Completed / Upper Secondary In...,9.210440,7.745013,0.0,Home - Personal Matters,Lunch,Tuesday,1,Commerce,Self-employed

In [136]:
summary = pd.DataFrame({
    "column": pod_23_3.columns,
    "dtype": pod_23_3.dtypes.values,
    "na_count": pod_23_3.isna().sum().values
})

# Function to get categories / unique values (limited for readability)
def get_values(col):
    if isinstance(col.dtype, pd.CategoricalDtype):
        return ", ".join(map(str, col.cat.categories))
    elif col.nunique() <= 10:
        return ", ".join(map(str, col.dropna().unique()))
    else:
        return "—"

summary["possible_values"] = [
    get_values(pod_23_3[col]) for col in pod_23_3.columns
]

summary.style.set_properties(**{"text-align": "left"})

# Saving new dataset

## Full dataset

In [137]:
pod_23_3.to_parquet("pod_23_3_full.parquet")

In [138]:
pod_23_3.shape

(94589, 17)

## Without work info

In [139]:
pod_23_3.drop(columns=["sector_comb", "empl_relat"]).shape

(94589, 15)

In [140]:
pod_23_3.drop(columns=["sector_comb", "empl_relat"]).to_parquet("pod_23_3_no-work-info.parquet")

## Only observations with work info

In [141]:
pod_23_3.loc[pod_23_3["sector_comb"].notna(), "empl_relat"].isna().sum()

np.int64(0)

In [142]:
pod_23_3.loc[pod_23_3["empl_relat"].notna(), "sector_comb"].isna().sum()

np.int64(0)

In [143]:
pod_23_3[pod_23_3["sector_comb"].notna()] \
    .drop(columns=["sector_comb", "empl_relat"]) \
    .shape

(69209, 15)

In [144]:
#pod_23_3[pod_23_3["sector_comb"].notna()] \
    #.reset_index(drop=True) \
    #.to_parquet("pod_23_3_workers.parquet")

pod_23_3[pod_23_3["sector_comb"].notna()] \
    .drop(columns=["curr_work"]) \
    .reset_index(drop=True) \
    .to_parquet("pod_23_3_workers.parquet")